/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package training.kafka.final_task.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Operation {
  ADD, SUBTRACT, DIVIDE, MULTIPLY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Operation\",\"namespace\":\"training.kafka.final_task.avro\",\"symbols\":[\"ADD\",\"SUBTRACT\",\"DIVIDE\",\"MULTIPLY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
